version: '3.8'

services:
  prompt-optimization:
    build: .
    ports:
      - "9080:9080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL:-gpt-4o}
      - HOST=0.0.0.0
      - PORT=9080
      - DEBUG=${DEBUG:-False}
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


