# 新版docker-compose不用写自动引用最新版本
# version: '3'

networks:
  frontend:
    external: true

services:                                      # 容器

  docker_jenkins:
    user: root                                 # root权限
    restart: always                            # 重启方式
    image: jenkins/jenkins:lts                 # 使用的镜像
    container_name: jenkins                    # 容器名称
    environment:
      - TZ=Asia/Shanghai
      - "JENKINS_OPTS=--prefix=/jenkins_home" ## 自定义 jenkins 访问前缀（上下文context）
    ports:                                     # 对外暴露的端口定义
      - 8080:8080
      - 50000:50000
    volumes:                                   # 卷挂载路径
      - /jenkins/jenkins_home/:/var/jenkins_home     # 挂载到容器内的jenkins_home目录
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose

  docker_nginx_pro:                            # nginx-pro环境
    restart: always
    image: nginx
    container_name: nginx_pro
    ports:
      - 8001:8001
    volumes:
      - /jenkins/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /jenkins/html:/usr/share/nginx/html  	 # 宿主机/docker/html 映射docker容器内的/usr/share/nginx/html
      - /jenkins/nginx/logs:/var/log/nginx

  docker_nginx_dev:                            # nginx-dev环境
    restart: always
    image: nginx
    container_name: nginx_dev
    ports:
      - 8002:8002
    volumes:
      - /jenkins/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /jenkins/html:/usr/share/nginx/html 		 # 宿主机/docker/html 映射docker容器内的/usr/share/nginx/html
      - /jenkins/nginx/logs:/var/log/nginx

